=== atovar67/Base-de-datos/BasedeDatos.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/BasedeDatos.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Configuracion SYSTEM "BasedeDatos.dtd">

    <Configuracion>
    ...
    </Configuracion>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Configuracion ((BaseDatos)*)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BaseDatos (Oficina, Sistema, IP_Host, Puerto, Usuario, Password, DatabaseName, TipoBasedeDatos)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Oficina (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Sistema (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT IP_Host (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Puerto (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Usuario (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Password (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DatabaseName (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT TipoBasedeDatos (#PCDATA)>

=== atovar67/Base-de-datos/BasedeDatos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE Configuracion SYSTEM "BasedeDatos.dtd">

<Configuracion>
    <BaseDatos>
        <Oficina>
            01
        </Oficina>
        <Sistema>
            Reg001
        </Sistema>
        <IP_Host>
            192.168.5.4
        </IP_Host>
        <Puerto>
            3309
        </Puerto>
        <Usuario>
            reportes
        </Usuario>
        <Password>
            reportes
        </Password>
        <DatabaseName>
            Reportes
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>
    <BaseDatos>
        <Oficina>
            00
        </Oficina>
        <Sistema>
            Reg001
        </Sistema>
        <IP_Host>
            192.168.5.4
        </IP_Host>
        <Puerto>
            3309
        </Puerto>
        <Usuario>
            remote
        </Usuario>
        <Password>
            E079D388
        </Password>
        <DatabaseName>
            r001
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>
    <BaseDatos>
        <Oficina>
            24
        </Oficina>
        <Sistema>
            CAAAREM3
        </Sistema>
        <IP_Host>
            192.168.5.1
        </IP_Host>
        <Puerto>
            3306
        </Puerto>
        <Usuario>
            superuser
        </Usuario>
        <Password>
            E079D388
        </Password>
        <DatabaseName>
            caaarem3
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>
    <BaseDatos>
        <Oficina>
            16
        </Oficina>
        <Sistema>
            CAAAREM3
        </Sistema>
        <IP_Host>
            192.168.3.1
        </IP_Host>
        <Puerto>
            3306
        </Puerto>
        <Usuario>
            superuser
        </Usuario>
        <Password>
            E079D388
        </Password>
        <DatabaseName>
            caaarem3
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>    
    <BaseDatos>
        <Oficina>
            17
        </Oficina>
        <Sistema>
            CAAAREM3
        </Sistema>
        <IP_Host>
            192.168.1.1
        </IP_Host>
        <Puerto>
            3306
        </Puerto>
        <Usuario>
            superuser
        </Usuario>
        <Password>
            E079D388
        </Password>
        <DatabaseName>
            caaarem3
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>
    <BaseDatos>
        <Oficina>
            47
        </Oficina>
        <Sistema>
            CAAAREM3
        </Sistema>
        <IP_Host>
            192.168.2.178
        </IP_Host>
        <Puerto>
            3306
        </Puerto>
        <Usuario>
            superuser
        </Usuario>
        <Password>
            E079D388
        </Password>
        <DatabaseName>
            caaarem3
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>
    <BaseDatos>
        <Oficina>
            43
        </Oficina>
        <Sistema>
            CAAAREM3
        </Sistema>
        <IP_Host>
            192.168.8.1
        </IP_Host>
        <Puerto>
            3306
        </Puerto>
        <Usuario>
            superuser
        </Usuario>
        <Password>
            E079D388
        </Password>
        <DatabaseName>
            caaarem3
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>      
    <BaseDatos>
        <Oficina>
            81
        </Oficina>
        <Sistema>
            CAAAREM3
        </Sistema>
        <IP_Host>
            192.168.7.1
        </IP_Host>
        <Puerto>
            3306
        </Puerto>
        <Usuario>
            superuser
        </Usuario>
        <Password>
            E079D388
        </Password>
        <DatabaseName>
            caaarem3
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>
    <BaseDatos>
        <Oficina>
            24
        </Oficina>
        <Sistema>
            ADUASIS
        </Sistema>
        <IP_Host>
            192.168.0.2
        </IP_Host>
        <Puerto>
            1433
        </Puerto>
        <Usuario>
            sa
        </Usuario>
        <Password>
            8uf3t3SQL
        </Password>
        <DatabaseName>
            adusism3
        </DatabaseName>
        <TipoBasedeDatos>
            SQLSERVER
        </TipoBasedeDatos>
    </BaseDatos>    
    <BaseDatos>
        <Oficina>
            99
        </Oficina>
        <Sistema>
            CAAAREM3
        </Sistema>
        <IP_Host>
            192.168.5.4
        </IP_Host>
        <Puerto>
            3309
        </Puerto>
        <Usuario>
            reportes
        </Usuario>
        <Password>
            reportes
        </Password>
        <DatabaseName>
            caaarem3
        </DatabaseName>
        <TipoBasedeDatos>
            MYSQL
        </TipoBasedeDatos>
    </BaseDatos>                                  
</Configuracion>
